### ISSUE TITLE
Supporting businesses 

### ISSUE THREAD

**Issue by nvk** [OPUASF/UASF#15]
### Who already supports UASF?

Company|Category|ANN.|
:--- | :--- | :---:
[Bitrefill](https://www.bitrefill.com) |Exchange| [proof](https://twitter.com/bitrefill/status/851818821946048512)
[Blocknomics](http://Blocknomics.co) |Explorer|  [proof](https://twitter.com/blockonomics_co/status/851770427529670658)
 [Bustabit](#) | Casino|[proof](https://www.reddit.com/r/Bitcoin/comments/63otrp/gregory_maxwell_major_asic_manufacturer_is/dfw02tg/)
[Coinkite](http://coinkite.com) | Hardware/Software | [proof](https://twitter.com/coinkite/status/851822761794260992)
[yogh.io](http://yogh.io) | Explorer| [proof](http://srv1.yogh.io/#json:getnetworkinfo)
[Trezor](https://trezor.io/) | Hardware Wallet | [proof](https://twitter.com/slushcz/status/851502735736418304)
[Samourai Wallet](https://samouraiwallet.com/) | Wallet| [proof](https://twitter.com/SamouraiWallet/status/851005717070917633)
[JoinMarket](https://github.com/JoinMarket-Org/joinmarket) | Mixer | [proof](https://twitter.com/joinmarket/status/851177740900368385)
[Freedom Node](https://freedomnode.com/) | ??? | [proof](https://freedomnode.com/bitcoin-core-support.txt)
[BitKong](https://bitkong.com/) | Casino | [proof](https://bitkong.com/segwit.txt)
[Bitfury](http://bitfury.com/) | Miner | [proof](https://news.bitcoin.com/bitfury-mines-block-signaling-uasf-segwit/)
[BitCoinReminder](https://bitcoinreminder.com/) | Tool | [proof](https://www.reddit.com/r/Bitcoin/comments/642n66/bitcoinremindercom_supports_bip148_and_a_fix/)

**Comment by chris-belcher** [comment]
BitRefill phone top up service (15k transactions per month)

https://twitter.com/bitrefill/status/851818821946048512

Bustabit bitcoin casino (apparently the biggest casino)

https://www.reddit.com/r/Bitcoin/comments/63otrp/gregory_maxwell_major_asic_manufacturer_is/dfw02tg/

JoinMarket (although it has zero power as everyone runs their own full node)

https://twitter.com/joinmarket/status/851177740900368385

**Comment by instagibbs** [comment]
@nvk can we get a table with two columns for both types of proposed UASFs?

**Comment by chris-belcher** [comment]
Some of these people don't distinguish between the types, so maybe a third column labeled like "supports UASF in principle".

Though from what I've seen it's the asicboost that most angers people.

**Comment by chris-belcher** [comment]
Slush / Trezor supports UASF

https://twitter.com/slushcz/status/851502735736418304

**Comment by nvk** [comment]
initial list live, addition can be done via PR on https://github.com/OPUASF/UASF/blob/master/README.md
