### ISSUE TITLE
Miner enforcement of BIP148

### ISSUE THREAD

**Issue by ghost** [OPUASF/UASF#4]
This section is incorrect:

> ### What do miners need to do to enforce BIP148?

> Miners should update their mining software to produce blocks with version bit 1 enabled prior to August 1st, 2017. Miners do not need to create SegWit blocks or make any other changes. After activation of SegWit, at a minimum, miners should also make sure they have a border node that filters out invalid blocks.

Miners need to be running a BIP148 node. Signalling segwit support is not enough. If a miner is signalling for segwit but not enforcing BIP148, on August 1st they'll follow the wrong side of the chain split.

**Comment by alp-bitcoin** [comment]
This is covered in the Border Node case.  Border Nodes will prevent them from following the wrong chain.

**Comment by ghost** [comment]
Wording is unclear. An alternative:

> Prior to August 1st, 2017, miners should either:
> 
> 1. Update their node software to a BIP148-enforcing version; or
> 1. Run a BIP148 border node to filter out invalid blocks, and update their existing mining software to produce blocks with version 1 bit enabled, to vote for Segwit activation
