### ISSUE TITLE
BIP 148 downloads should be made available

### ISSUE THREAD

**Issue by luke-jr** [OPUASF/UASF#53]
Due to #52, it may be reasonable to publish binaries to avoid a risk of people looking for them and finding malware. Ideally there should also be more gitian signers.

Due to the inherent need to trust PPA (cannot be gitian-built), I made an Ubuntu PPA here: https://launchpad.net/~luke-jr/+archive/ubuntu/bitcoin-core-bip148-unofficial-builds

**Comment by alp-bitcoin** [comment]
Binaries will be available if there is significant support, and only then.
