### ISSUE TITLE
Add links to machine translations

### ISSUE THREAD

**Issue by unsystemizer** [OPUASF/UASF#69]
Example for Simplified Chinese: http://www.microsofttranslator.com/bv.aspx?from=&to=zh-CHT&a=http%3A%2F%2Fuasf.co

These could be added in template header or footer. 

I should probably add that:

* Google is blocked in China
* the MS translator isn't bad or blocked

**Comment by nvk** [comment]
Sure, add to the footer as PR.

**Comment by unsystemizer** [comment]
I'm afraid most users who can't read English wouldn't scroll to the bottom, so I added it to top. It uglifies the site a bit, but it's much more effective that way.

But feel free to move the added segment to the bottom (edits from maintainers are allowed).

**Comment by nvk** [comment]
Added Google widget.
